### PR TITLE
MSVC Compatibility fix for timer

### PR DESCRIPTION
**Pull request by richinseattle**
use clock() instead of gettimeofday() for cross-platform compatibility

### CODE REVIEW

**Comment by karpathy** [comment]
I just changed it the other way around. clock() measures CPU time, doesn't report correct time when using OpenMP

**Comment by richinseattle** [comment]
Ah, on Windows clock() measures wall time but cpu time on posix.. I'm not sure how to avoid an ifdef to reliably get wall time cross platform. My original patch with GetTickCount() is the closest replacement for gettimeofday()

**Comment by richinseattle** [comment]
I've tested timespec_get() on Windows and Linux with openmp and it appears to work as expected for wall clock time

**Comment by karpathy** [comment]
ok let's try.

**Pull request merged**
