### PR TITLE
Add Windows mmap & timing compatibility

### PR DESCRIPTION
**Pull request by tairov**
Compilation on Windows platform was broken after merging mmap PR #50 
This PR add compatibility as it was suggested in this issue #91 

CI: https://github.com/tairov/llama2.c/actions/runs/5664313188/job/15347372920

### CODE REVIEW

**Comment by karpathy** [comment]
@tairov this fixes both timing and mmap for windows, right? can you say a bit more about where this code comes from? i expect there are no easy alternatives that don't require additional files to be added to the project?

**Comment by xunboo** [comment]
I got the mmap file from https://github.com/m-labs/uclibc-lm32/blob/master/utils/mmap-windows.c
However, I suggest use .h instead of .c for header name

**Comment by tairov** [comment]
@karpathy yes, it fixes issue with timing and mmap.
As @xunboo mentioned `mmap-windows.c` is from  [uclibc-lm32 repo](https://github.com/m-labs/uclibc-lm32/blob/master/utils/mmap-windows.c) with [GPL v2.1 License](https://github.com/m-labs/uclibc-lm32/blob/master/COPYING.LIB)

I would say there is no simple solution that can keep `run.c` simple without additional file with encapsulated windows logic `mmap/CreateFileMappingA`.
I think it's much more easier to maintain code by having `#if #else` pragma check to make it compatible with Windows.
`llama.cpp` also uses `#if defined(_WIN32)` checks but directly from [source](https://github.com/ggerganov/llama.cpp/blob/32c54116318929c90fd7ae814cf9b5232cd44c36/llama-util.h#L212-L211) 

Considering that the beauty of this repository is its simplicity, and also considering the requests of the community to [keep things simple](#104), I see this solution with an additional file as more reasonable for supporting the Windows platform.

**Comment by tairov** [comment]
Simplified `time_in_ms`, got rid of `#ifdefs`. 
Moved `mmap & clock_gettime` ported versions to `win.h` that is included in a single place in `run.c` with apparently inevitable `#if defined` pragma check.

**Comment by karpathy** [comment]
@tairov IANAL etc but isn't GPL code not compatible with this repo, if it is under MIT?

**Comment by tairov** [comment]
Generally yes, seems that GPL is not compatible with MIT.
Since we're using this file only https://github.com/m-labs/uclibc-lm32/blob/master/utils/mmap-windows.c , it says 
```
 * Placed into the public domain
```

ChatGPT meaning on this 😄  : 

> Public domain code refers to software that is not protected by copyright. It is available for anyone to use for any purpose, without needing to obtain permission or pay licensing fees.

**Comment by richinseattle** [comment]
I've fixed these issues in my fork yesterday, including the fix for timer, mmap (using the mman-win32), and also today fixed the openmp pragmas to work with msvc. Compiles with msvc or cross-compile with mingw32. Makefile target and a .bat added for building.
https://github.com/richinseattle/llama2.c

**Comment by karpathy** [comment]
@tairov in this version how does the windows-specific version of `clock_gettime` end up getting called? There's no ifdef needed?

**Comment by richinseattle** [comment]
The function implementation is hidden in the win.h header so the only ifdef is in the includes. Not a bad way to do it.

**Comment by tairov** [comment]
@karpathy I simplified `run.c` and `clock_gettime` alternative that is also moved to [win.h:#112](https://github.com/karpathy/llama2.c/pull/96/files#diff-72db5fdcbf1e9ca253896088a1a03b3704e927562a67f9ff8d4378e367c4fec7R112)
Overall `win.h` now contains 112 lines and solves both existing issues with compilations on windows

**Comment by karpathy** [comment]
Merged the other fork but ty @tairov for all the help here!

**Pull request closed without merging**
