### PR TITLE
Bigger number better with -funsafe-math-optimizations flag.

### PR DESCRIPTION
**Pull request by luigifcruz**
Enabling spicy math optimization `-funsafe-math-optimizations` yields ~6x performance uplift. 

Screenshot 2023-07-23 at 5 05 50 PM

### CODE REVIEW

**Comment by karpathy** [comment]
I am happy to mention this in README, but only as an optional thing. I saw some mixed results with it on Twitter?

**Comment by luigifcruz** [comment]
Sounds good. I can't find anyone having problems with it on Twitter. But I'll turn it into an optional flag in the README.

**Comment by luigifcruz** [comment]
Done, the flag is now optional in the README.

**Comment by karpathy** [comment]
Sorry I didn't mean problems, it's just someone on Twitter said that including this made no difference to them, or something. Maybe I'm making this up. In any case, merged for now thank you for pointing it out!

**Comment by luigifcruz** [comment]
Cool! Thanks for merging.

**Pull request merged**
