### PR TITLE
Refactor freqs_cis into freqs_cos and freqs_sin

### PR DESCRIPTION
**Pull request by ai-doge**
Refactor freqs_cis into freqs_cos and freqs_sin
remove complex64 for ONNX export compatibility

### CODE REVIEW

**Comment by vgoklani** [comment]
Can the updated model be compiled with the torch.compile() function?

**Comment by tcapelle** [comment]
The `torch.polar` solution was so elegant 😭

**Comment by dongwangdw** [comment]
> The `torch.polar` solution was so elegant 😭

yes, agree. But currently triton does not support complex value which is the backend of pytorch.

**Review by dongwangdw — COMMENTED** [review]
```
        serialize(self.freqs_cis.real[:p.max_seq_len])
        serialize(self.freqs_cis.imag[:p.max_seq_len])
```
With your change, this freqs_cis is not registered here
These two lines should be fix too. As I tried to compile and it failed at this.

**Comment by ai-doge** [comment]
> @ai-doge
> 
> ```
>         serialize(self.freqs_cis.real[:p.max_seq_len])
>         serialize(self.freqs_cis.imag[:p.max_seq_len])
> ```
> 
> With your change, this freqs_cis is not registered here These two lines should be fix too. As I tried to compile and it failed at this.

Thank you for pointing out the error, the issue has been fixed.

**Comment by karpathy** [comment]
Thank you for this PR. The official Meta implementations of Llama2 should have imo used an implementation along these lines. Complex64 does not have enough existing support on ONNX, torch.compile, and is unnecessarily confusing to (I expect most) people not familiar with complex numbers.

**Comment by vgoklani** [comment]
Hey @ai-doge @dongwangdw Are you able to use torch.compile() on the updated code? I get a stack-trace, where it hits the config.cache_size_limit (64)... thanks!

**Pull request merged**
