### PR TITLE
Fuse q, k, v matmuls

### PR DESCRIPTION
**Pull request by Maknee**
PR fuses qkv matmuls.

Below are benchmarks per make recipe using [hyperfine](https://github.com/sharkdp/hyperfine) benchmarking tool, comparing the performance between the original `run` (no fuse) and `run_qkv` (fused qkv matmuls)

# run

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 5 --runs 10 "./run model.bin 0.0" "./run_qkv model.bin 0.0"
Benchmark 1: ./run model.bin 0.0
  Time (mean ± σ):      2.028 s ±  0.001 s    [User: 2.012 s, System: 0.016 s]
  Range (min … max):    2.026 s …  2.031 s    10 runs
 
Benchmark 2: ./run_qkv model.bin 0.0
  Time (mean ± σ):      1.873 s ±  0.023 s    [User: 1.856 s, System: 0.017 s]
  Range (min … max):    1.858 s …  1.925 s    10 runs
 
Summary
  ./run_qkv model.bin 0.0 ran
    1.08 ± 0.01 times faster than ./run model.bin 0.0
```

---

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 5 --runs 10 "./run model44m.bin 0.0" "./run_qkv model44m.bin 0.0"
Benchmark 1: ./run model44m.bin 0.0
  Time (mean ± σ):      6.238 s ±  0.130 s    [User: 6.194 s, System: 0.044 s]
  Range (min … max):    6.136 s …  6.402 s    10 runs
 
Benchmark 2: ./run_qkv model44m.bin 0.0
  Time (mean ± σ):      5.514 s ±  0.102 s    [User: 5.469 s, System: 0.045 s]
  Range (min … max):    5.416 s …  5.631 s    10 runs
 
Summary
  ./run_qkv model44m.bin 0.0 ran
    1.13 ± 0.03 times faster than ./run model44m.bin 0.0
```

# runfast

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 5 --runs 10 "./run model.bin 0.0" "./run_qkv model.bin 0.0"
Benchmark 1: ./run model.bin 0.0
  Time (mean ± σ):     495.9 ms ±   3.9 ms    [User: 479.5 ms, System: 16.4 ms]
  Range (min … max):   490.6 ms … 500.8 ms    10 runs
 
Benchmark 2: ./run_qkv model.bin 0.0
  Time (mean ± σ):     465.9 ms ±   6.4 ms    [User: 450.6 ms, System: 15.2 ms]
  Range (min … max):   454.5 ms … 473.0 ms    10 runs

Summary
  ./run_qkv model.bin 0.0 ran
    1.06 ± 0.02 times faster than ./run model.bin 0.0
```

---

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 5 --runs 10 "./run model44m.bin 0.0" "./run_qkv model44m.bin 0.0"
Benchmark 1: ./run model44m.bin 0.0
  Time (mean ± σ):      1.733 s ±  0.002 s    [User: 1.685 s, System: 0.048 s]
  Range (min … max):    1.730 s …  1.737 s    10 runs
 
Benchmark 2: ./run_qkv model44m.bin 0.0
  Time (mean ± σ):      1.647 s ±  0.002 s    [User: 1.597 s, System: 0.050 s]
  Range (min … max):    1.645 s …  1.651 s    10 runs
 
Summary
  ./run_qkv model44m.bin 0.0 ran
    1.05 ± 0.00 times faster than ./run model44m.bin 0.0
```

# runomp

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 10 --runs 100 "OMP_NUM_THREADS=8 ./run model.bin 0.0" "OMP_NUM_THREADS=8 ./run_qkv model.bin 0.0"
Benchmark 1: OMP_NUM_THREADS=8 ./run model.bin 0.0
  Time (mean ± σ):      59.3 ms ±   3.8 ms    [User: 368.2 ms, System: 15.7 ms]
  Range (min … max):    57.4 ms …  89.3 ms    100 runs
 
Benchmark 2: OMP_NUM_THREADS=8 ./run_qkv model.bin 0.0
  Time (mean ± σ):      55.5 ms ±   2.2 ms    [User: 338.8 ms, System: 14.8 ms]
  Range (min … max):    53.5 ms …  74.6 ms    100 runs
 
Summary
  OMP_NUM_THREADS=8 ./run_qkv model.bin 0.0 ran
    1.07 ± 0.08 times faster than OMP_NUM_THREADS=8 ./run model.bin 0.0
```

---

```
maknee@maknee-gpu:~/llama2.c$ hyperfine --warmup 10 --runs 100 "OMP_NUM_THREADS=8 ./run model44m.bin 0.0" "OMP_NUM_THREADS=8 ./run_qkv model44m.bin 0.0"
Benchmark 1: OMP_NUM_THREADS=8 ./run model44m.bin 0.0
  Time (mean ± σ):      59.3 ms ±   2.2 ms    [User: 368.1 ms, System: 15.7 ms]
  Range (min … max):    57.7 ms …  79.9 ms    100 runs

Benchmark 2: OMP_NUM_THREADS=8 ./run_qkv model44m.bin 0.0
  Time (mean ± σ):      56.1 ms ±   3.2 ms    [User: 342.4 ms, System: 15.5 ms]
  Range (min … max):    54.5 ms …  79.7 ms    100 runs

Summary
  OMP_NUM_THREADS=8 ./run_qkv model.bin 0.0 ran
    1.06 ± 0.07 times faster than OMP_NUM_THREADS=8 ./run model.bin 0.0
```

Here are the specs of the machine/env I'm running on

```
AMD Ryzen 7 7800X3D 8-Core Processor
128GB DDR5 5200 ram
```
```
Linux maknee-gpu 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 
```

### CODE REVIEW

**Comment by karpathy** [comment]
This is quite nice, sadly it bloats the code quite a bit in terms of LOC.... hard

**Comment by karpathy** [comment]
wow, very interesting. is this somehow tiling the qkv matmul into 4 * 4 = 16 nested loops? so it's 16X unrolled?

**Comment by Maknee** [comment]
Reduced the LOC. Performance uplift varies from original.

Old:

| | % uplift (model) | % uplift (model44m) |
| - |----------- | ----------- |
| run | 1.08 | 1.13|
| runfast| 1.06| 1.05|
| runomp| 1.07 | 1.06|


New:

| | % uplift (model) | % uplift (model44m) |
| - |----------- | ----------- |
| run | 1.08 | 1.14|
| runfast| 1.04| 1.01|
| runomp| 1.02| 1.13|

---

## run

```
Benchmark 1: ./run model.bin 0.0
  Time (mean ± σ):      2.030 s ±  0.002 s    [User: 2.010 s, System: 0.020 s]
  Range (min … max):    2.028 s …  2.032 s    10 runs
 
Benchmark 2: ./run_qkv model.bin 0.0
  Time (mean ± σ):      1.875 s ±  0.002 s    [User: 1.855 s, System: 0.020 s]
  Range (min … max):    1.873 s …  1.877 s    10 runs
 
Summary
  ./run_qkv model.bin 0.0 ran
    1.08 ± 0.00 times faster than ./run model.bin 0.0
```

---

```
Benchmark 1: ./run model44m.bin 0.0
  Time (mean ± σ):      6.301 s ±  0.128 s    [User: 6.243 s, System: 0.057 s]
  Range (min … max):    6.151 s …  6.402 s    10 runs

Benchmark 2: ./run_qkv model44m.bin 0.0
  Time (mean ± σ):      5.527 s ±  0.056 s    [User: 5.470 s, System: 0.057 s]
  Range (min … max):    5.483 s …  5.624 s    10 runs
 
Summary
  ./run_qkv model44m.bin 0.0 ran
    1.14 ± 0.03 times faster than ./run model44m.bin 0.0
```

## runfast

```
Benchmark 1: ./run model.bin 0.0
  Time (mean ± σ):     496.7 ms ±   5.5 ms    [User: 478.9 ms, System: 17.7 ms]
  Range (min … max):   488.8 ms … 504.0 ms    10 runs
 
Benchmark 2: ./run_qkv model.bin 0.0
  Time (mean ± σ):     478.6 ms ±   2.8 ms    [User: 457.8 ms, System: 20.8 ms]
  Range (min … max):   475.5 ms … 484.5 ms    10 runs
 
Summary
  ./run_qkv model.bin 0.0 ran
    1.04 ± 0.01 times faster than ./run model.bin 0.0
```

---

```
Benchmark 1: ./run model44m.bin 0.0
  Time (mean ± σ):      1.742 s ±  0.001 s    [User: 1.684 s, System: 0.058 s]
  Range (min … max):    1.741 s …  1.743 s    10 runs
 
Benchmark 2: ./run_qkv model44m.bin 0.0
  Time (mean ± σ):      1.729 s ±  0.004 s    [User: 1.670 s, System: 0.058 s]
  Range (min … max):    1.723 s …  1.736 s    10 runs
 
Summary
  ./run_qkv model44m.bin 0.0 ran
    1.01 ± 0.00 times faster than ./run model44m.bin 0.0
```

## runomp

```
Benchmark 1: ./run model.bin 0.0
  Time (mean ± σ):      61.9 ms ±   0.9 ms    [User: 367.3 ms, System: 21.0 ms]
  Range (min … max):    60.9 ms …  63.1 ms    10 runs
 
Benchmark 2: ./run_qkv model.bin 0.0
  Time (mean ± σ):      62.9 ms ±   0.8 ms    [User: 378.3 ms, System: 16.0 ms]
  Range (min … max):    61.7 ms …  64.3 ms    10 runs
 
Summary
  ./run model.bin 0.0 ran
    1.02 ± 0.02 times faster than ./run_qkv model.bin 0.0
```

---

```
Benchmark 1: ./run model44m.bin 0.0
  Time (mean ± σ):     585.8 ms ±   5.6 ms    [User: 4262.3 ms, System: 60.5 ms]
  Range (min … max):   580.2 ms … 596.8 ms    10 runs
 
Benchmark 2: ./run_qkv model44m.bin 0.0
  Time (mean ± σ):     517.9 ms ±   1.6 ms    [User: 3716.6 ms, System: 62.5 ms]
  Range (min … max):   515.8 ms … 519.6 ms    10 runs
 
Summary
  ./run_qkv model44m.bin 0.0 ran
    1.13 ± 0.01 times faster than ./run model44m.bin 0.0
```

**Comment by Maknee** [comment]
> wow, very interesting. is this somehow tiling the qkv matmul into 4 * 4 = 16 nested loops? so it's 16X unrolled?

Seems so, looking at the [generated assembly in godbolt](https://godbolt.org/z/f4vGe1ac7)

**Comment by krzysztof-jusiak** [comment]
Very clever change. It doesn't add too much complexity but I don't think it will be understood by everyone, if that's the goal of the project (just pointing it out, not saying that it shouldn't get in if it's worth it). If I'm reading it correctly though it seems that the performance gain is small looking at the average runs, is the tok/s much better? On the other hand, I also think it's a great example of why declarative computation graphs are so powerful, having easy to follow user interface and fused/optimized back-end is extremely powerful concept but that' defo not 500 lines of easy to follow code.

**Comment by axrwl** [comment]
Clever indeed. #75 should also show similar improvements in performance.

**Comment by karpathy** [comment]
Thank you this is clever but I think for now I want to try to keep a single matmul function, which can become a single point of heavy optimization.

**Pull request closed without merging**
