### PR TITLE
[Feat]: Add support for meta llama hf model conversion

### PR DESCRIPTION
**Pull request by Nick-infinity**
Description:
Llama 2 hf models have weights stored with diff name

### CODE REVIEW

**Comment by Nick-infinity** [comment]
Just parking it here for others. Merge is not required

**Comment by karpathy** [comment]
I'll take it because i expect a lot of finetunes will be in HF format. Ty.

**Comment by mukel** [comment]
The HF models apply a permutation to k and v, so the RoPE is different fro the original Llama 2 models. The permutation must be undone to export from HF to llam2a.c's simple .bin files.
It took me quite some time to figure this out, the symptom is it starts degenerating and printing gibberish after ~20 or more tokens.

**Comment by Nick-infinity** [comment]
Yes , I have noticed the gibberish too. That's why I left the comment in
the script for RoPe encodings extraction.

Thanks for validating it

**Comment by karpathy** [comment]
... PR fix welcome

**Comment by calvintwr** [comment]
I don't think this is working. https://github.com/karpathy/llama2.c/issues/314

**Comment by atamurad** [comment]
> The HF models apply a permutation to wq and wk, so the RoPE is different fro the original Llama 2 models. The permutation must be undone to export from HF to llam2a.c's simple .bin files. It took me quite some time to figure this out, the symptom is it starts degenerating and printing gibberish after ~20 or more tokens.
> 
> See https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py#L113-L115

@mukel thanks for tracking this down, fixed it here: https://github.com/karpathy/llama2.c/pull/326

**Pull request merged**
