### PR TITLE
Added Go ports

### PR DESCRIPTION
**Pull request by nikolaydubina**
Hello,

I have made few days ago Go port of this model. It is different from other Go port. It follows typical Go standard and notations better while preserving style of llama2.c

> I also think I did Go port first. haha !
> UPD: I see other versions of it popup: https://github.com/haormj/llama2.go so it is debatable who is first, if that matters anyways.

Anyways,

Would be great to include it here!

Thank you!

### CODE REVIEW

**Comment by saracen** [comment]
I also created one: https://github.com/saracen/llama2.go

Separate from the others I guess in that it's dependency free, implements mmap, concurrency and I'm trying to eliminate bound checks where possible.

@karpathy Happy to add unless it feels like we're overcrowding the README with Go ports :smile:. Let me know.

**Comment by karpathy** [comment]
gosh, haha!

**Comment by tmc** [comment]
Gophers galore! Sounds like we need to get collaborating on one!

I believe mine is the most faithful line by line port and definitely want to increase performance while tracking fidelity to the c implementation.

**Comment by kroggen** [comment]
The "bad locality" problem was fixed, but your ports all still have it

You can check [here](https://github.com/karpathy/llama2.c/pull/99/files) how it was made

**Comment by nikolaydubina** [comment]
thanks. will look into it !

> your ports

haha. not really my ports ! I maintain only one

and original port (https://github.com/tmc/go-llama2/blob/master/go/run.go#L352) still has it too 🤷🏻‍♂️

---

speaking of solution, I see `memset`, Go does not have it. so need to see if we can adjust it for Go.

**Pull request merged**
