### PR TITLE
Refactor RoPE code using complex

### PR DESCRIPTION
**Pull request by shiwenloong**
This commit use complex to refactor the code responsible for RoPE. Instead of using a nested loop over the number of heads, it now utilizes a single loop iterating over the combined size of the heads and the head size. This modification improves code readability and makes the code more amenable to parallelization.

### CODE REVIEW

**Comment by mrsteyk** [comment]
Can confirm this simplifies code generation on clang 15.0.7. Only one if is done versus multiple comparisons and 3 vectorised code blocks.
image

**Comment by joey00072** [comment]
Thats so cool, also add comment explaintion

**Comment by mrsteyk** [comment]
Upon closer inspection this seems to hinder wider lane parallelisation.
image

**Comment by kroggen** [comment]
Some benchmarks: (tokens / second)

Linux and gcc 11.3.0:

| | prev | new
| -----| ------| -------
| runfast | 228 | 271
| runomp | 257 | 322

MacBook and clang 14.0.3:

| | prev | new
| -----| ------| -------
| runfast | 115 | 116

**Comment by mrsteyk** [comment]
Slowdowns might be due to extra checks for pointer alignment. Also on Mac try adding `-fveclib=Accelerate` @kroggen (adding `-fveclib=libmvec` helps glibc Linux with clang).

**Comment by mrsteyk** [comment]
Size of `Config` prevents proper wider lane utilisation (28 is not 16 aligned).
image

**Comment by kroggen** [comment]
You can add a new 32bit element on config and benchmark

**Comment by xefoci7612** [comment]
Maybe this is faster, though not tested for speed but verified it works correctly and result is equivalent to current implementation.

```C
        // Set up vectors to be paired with q and k for RoPE
        for (int i = 0; i < p->n_heads * head_size; i+=2) {
            s->qi[i]   = -s->q[i+1];
            s->qi[i+1] =  s->q[i];
            s->ki[i]   = -s->k[i+1];
            s->ki[i+1] =  s->k[i];
        }

        // apply RoPE rotation to the q and k vectors for each head
        int i, k;
        #pragma omp parallel for private(i)
        // rotate q and k by the freq_cis_real and freq_cis_imag
        for (int i = 0; i <  p->n_heads * head_size; i++) {
            k = (i % head_size) / 2;
            s->q[i] = s->q[i] * freq_cis_real_row[k] + s->qi[i] * freq_cis_imag_row[k];
            s->k[i] = s->k[i] * freq_cis_real_row[k] + s->ki[i] * freq_cis_imag_row[k];
        }
```

Here the idea is to use 2 support vectors qi and ki for the pairing with q and k.

The advantage is that in the main loop the formulas use a single index i instead of the intermixed i and i+1 so should be easier to parallelize.

**Comment by mrsteyk** [comment]
Compiled like so:

```bash
clang -fveclib=libmvec -fno-math-errno -fno-stack-protector -no-pie -Ofast -fopenmp -march=native run.c -lm  -o run
```

Results:
```
# Original
OMP_NUM_THREADS=6 ./run ./out/model.bin 0
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red ball in the sky. It was the sun! She thought it was so pretty.
Lily wanted to play with the ball, but it was too high up in the sky. She tried to jump and reach it, but she couldn't. Then, she had an idea. She would use a stick to knock the ball down.
Lily found a stick and tried to hit the ball. But the stick was too short. She tried again and again, but she couldn't reach it. She felt sad.
Suddenly, a kind man came by and saw Lily. He asked her what was wrong. Lily told him about the ball. The man smiled and said, "I have a useful idea!" He took out a long stick and used it to knock the ball down. Lily was so happy! She thanked the man and they played together in the sunshine.
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red
achieved tok/s: 496.108949

# PR (yes I get exact same results)
OMP_NUM_THREADS=6 ./run_199 ./out/model.bin 0
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red ball in the sky. It was the sun! She thought it was so pretty.
Lily wanted to play with the ball, but it was too high up in the sky. She tried to jump and reach it, but she couldn't. Then, she had an idea. She would use a stick to knock the ball down.
Lily found a stick and tried to hit the ball. But the stick was too short. She tried again and again, but she couldn't reach it. She felt sad.
Suddenly, a kind man came by and saw Lily. He asked her what was wrong. Lily told him about the ball. The man smiled and said, "I have a useful idea!" He took out a long stick and used it to knock the ball down. Lily was so happy! She thanked the man and they played together in the sunshine.
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red
achieved tok/s: 496.108949

# Added extra 4 bytes at the beg
OMP_NUM_THREADS=6 ./run_32 ./out/model_32.bin 0
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red ball in the sky. It was the sun! She thought it was so pretty.
Lily wanted to play with the ball, but it was too high up in the sky. She tried to jump and reach it, but she couldn't. Then, she had an idea. She would use a stick to knock the ball down.
Lily found a stick and tried to hit the ball. But the stick was too short. She tried again and again, but she couldn't reach it. She felt sad.
Suddenly, a kind man came by and saw Lily. He asked her what was wrong. Lily told him about the ball. The man smiled and said, "I have a useful idea!" He took out a long stick and used it to knock the ball down. Lily was so happy! She thanked the man and they played together in the sunshine.
<s>
Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red
achieved tok/s: 500.000000
```

But my results fluctuate a lot

**Comment by shiwenloong** [comment]
> This commit refactors the code responsible for RoPE. Instead of using a nested loop over the number of heads, it now utilizes a single loop iterating over the combined size of the heads and the head size. This modification improves code readability and makes the code more amenable to parallelization.

Now the code is further  simplified using complex. This modification improves the code readability.

**Comment by xefoci7612** [comment]
> > This commit refactors the code responsible for RoPE. Instead of using a nested loop over the number of heads, it now utilizes a single loop iterating over the combined size of the heads and the head size. This modification improves code readability and makes the code more amenable to parallelization.
> 
> Now the code is further simplified using complex. This modification improves the code readability.

Very nice! Definitely the best solution.

Sorry for nitpicking, but is there a reason why you prefer `float _Complex` to `float complex`?

**Comment by mrsteyk** [comment]
With this new change it is consistently faster than original and padded.

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./run_199 /tmp/model.bin 0` | 461.9 ± 5.4 | 458.9 | 477.3 | 1.00 |
| `./run /tmp/model.bin 0` | 475.8 ± 0.9 | 473.6 | 477.7 | 1.03 ± 0.01 |
| `./run_32 /tmp/model_32.bin 0` | 475.8 ± 1.2 | 473.4 | 480.7 | 1.03 ± 0.01 |
| `./run_64 /tmp/model_64.bin 0` | 478.6 ± 0.9 | 476.2 | 480.1 | 1.04 ± 0.01 |

The code also looks simpler (on clang 15), with only simd instructions in a row.
image

**Comment by mrsteyk** [comment]
Determinism for the last token is broken, this fixes it (outputs `but` instead of `red`)
```cpp
for (int i = 0; i < p->n_heads; i++) {
    for (int j = 0; j <  head_size / 2; j++) {
        float _Complex f = freq_cis_real_row[j] + freq_cis_imag_row[j] * I;
        q_c[(i * head_size / 2) + j] *= f;
        k_c[(i * head_size / 2) + j] *= f;
    }
}
```

**Comment by kroggen** [comment]
@mrsteyk I don't understand this assembly output. Is it computing `p->n_heads * head_size / 2` at every iteration?
If yes, then it could be computed before and use just the result on the for loop.

**Comment by mrsteyk** [comment]
> @mrsteyk I don't understand this assembly output. Is it computing `p->n_heads * head_size / 2` at every iteration? If yes, then it could be computed before and use just the result on the for loop.

This is not assembly. But yes it does appear this way.
```nasm
mov     rdx, [rsp+128h+var_D8]
mov     ebp, [rsp+128h+var_E0]
imul    ebp, [rdx+0Ch]
inc     rcx
mov     edi, ebp
shr     edi, 1Fh
add     edi, ebp
sar     edi, 1
movsxd  rdi, edi
cmp     rcx, rdi
jl      short loc_402A00
```

**Comment by kroggen** [comment]
The compiler should check if these values are changed in the loop and then use a fixed value there if not.

Here is a version with a single loop:

```c
int total_iterations = p->n_heads * (head_size / 2);

for (int index = 0; index < total_iterations; index++) {
    int i = index / (head_size / 2);
    int j = index % (head_size / 2);

    float _Complex f = freq_cis_real_row[j] + freq_cis_imag_row[j] * I;
    q_c[index] *= f;
    k_c[index] *= f;
}
```

And another one:

```c
int total_iterations = p->n_heads * (head_size / 2);
int i = 0;
int j = 0;

for (int index = 0; index < total_iterations; index++) {
    float _Complex f = freq_cis_real_row[j] + freq_cis_imag_row[j] * I;
    q_c[index] *= f;
    k_c[index] *= f;

    j++;
    if (j == head_size / 2) {
        j = 0;
        i++;
    }
}
```

Although less readable

**Comment by mrsteyk** [comment]
> The compiler should check if these values are changed in the loop and then use a fixed value there if not.

You cannot have this guaranntee when using pointers. Clang also doesn't appear to take `restrict`s into consideration and still compares pointers for wider lane utilisation (appears to happen on AVX enabled target if size is constant).

**Comment by mrsteyk** [comment]
On my machine the newer change emits `idiv`, needless to say it still recomputes every time it checks.

**Comment by kroggen** [comment]
`/ 2` should be converted to a right shift of 1. these compilers are not so smart...

**Comment by mrsteyk** [comment]
> `/ 2` should be converted to a right shift of 1. these compilers are not so smart...

That's where you are wrong, idiv is required for modulo operation. Division by 2 is already a shift.

**Comment by shiwenloong** [comment]
> > > This commit refactors the code responsible for RoPE. Instead of using a nested loop over the number of heads, it now utilizes a single loop iterating over the combined size of the heads and the head size. This modification improves code readability and makes the code more amenable to parallelization.
> > 
> > 
> > Now the code is further simplified using complex. This modification improves the code readability.
> 
> Very nice! Definitely the best solution.
> 
> Sorry for nitpicking, but is there a reason why you prefer `float _Complex` to `float complex`?
> 
> Also a possible optimization would be pre-arrange w->freq_cis_real and w->freq_cis_imag in a w->freq_cis complex vector at startup so to avoid calculating in the loop:
> 
> `float complex f = freq_cis_real_row[i] + freq_cis_imag_row[i] * I;`
> 
> and just write
> 
> ```c
>             q_c[i] *= freq_cis[i];
>             k_c[i] *= freq_cis[i];
> ```

Thanks. `float complex` is better than `float _Complex`. The code has been changed to use `float complex`.

**Comment by shiwenloong** [comment]
> On my machine the newer change emits `idiv`, needless to say it still recomputes every time it checks.

Does this mean that `i % (head_size / 2)` will be computed twice?

**Comment by mrsteyk** [comment]
> > On my machine the newer change emits `idiv`, needless to say it still recomputes every time it checks.
> 
> 
> 
> Does this mean that `i % (head_size / 2)` will be computed twice?

No, but it is computed every iteration i changes. Also a block for next instructions since they rely on result of idiv.

**Comment by xefoci7612** [comment]
Yes modulo operation is quiet expensive. Not very good to use it if not really necessary.

IMHO better to revert to original code without modulo % and instead better understand from where it comes out the off-by-one issue on the last token and fix just that.

**Comment by shiwenloong** [comment]
> > > On my machine the newer change emits `idiv`, needless to say it still recomputes every time it checks.
> > 
> > 
> > Does this mean that `i % (head_size / 2)` will be computed twice?
> 
> No, but it is computed every iteration i changes. Also a block for next instructions since they rely on result of idiv.

Perhaps this modification can eliminate the issue？
```
for (int h = 0; h < p->n_heads; h++) {
    float complex* q_c = (float complex*)(s->q + h * head_size);
    float complex* k_c = (float complex*)(s->k + h * head_size);
    for (int i = 0; i < head_size / 2; i+=1) {
        float complex f = freq_cis_real_row[i] + freq_cis_imag_row[i] * I;
        q_c[i] *= f;
        k_c[i] *= f;
    }
}
```

**Comment by kroggen** [comment]
Without modulo:
```c
float complex* q_complex = (float complex*) s->q;
float complex* k_complex = (float complex*) s->k;
int half_head_size = head_size / 2;
int total_iterations = p->n_heads * half_head_size;
int j = 0;
for (int i = 0; i < total_iterations; i++) {
    q_complex[i] *= freq_cis_row[j];
    k_complex[i] *= freq_cis_row[j];
    j++;
    if(j == half_head_size) {
        j = 0;
    }
}
```

Or more readable:

```c
float complex* q_complex = (float complex*) s->q;
float complex* k_complex = (float complex*) s->k;
int j = 0;
for (int i = 0; i < p->n_heads * head_size / 2; i++) {
    q_complex[i] *= freq_cis_row[j];
    k_complex[i] *= freq_cis_row[j];
    j++;
    if(j == head_size / 2) {
        j = 0;
    }
}
```

**Comment by mrsteyk** [comment]
> Perhaps this modification can eliminate the issue？
> 
> ```
> for (int h = 0; h < p->n_heads; h++) {
>     float complex* q_c = (float complex*)(s->q + h * head_size);
>     float complex* k_c = (float complex*)(s->k + h * head_size);
>     for (int i = 0; i < head_size / 2; i+=1) {
>         float complex f = freq_cis_real_row[i] + freq_cis_imag_row[i] * I;
>         q_c[i] *= f;
>         k_c[i] *= f;
>     }
> }
> ```

Yes, as I outlined [here](https://github.com/karpathy/llama2.c/pull/199#issuecomment-1659899888). My results should also be taken with a grain of salt because my CPU is vulnerable and fixes eat performance, bugs field is `cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_stale_data retbleed`. And as @kroggen noted, because `p->n_heads` is a pointer based read, you need to cache it, because compiler thinks there can be side effects.

```cpp
const int n_heads = p->n_heads;
for (int h = 0; h < n_heads; h++) {
    float complex* q_c = (float complex*)(s->q + h * head_size);
    float complex* k_c = (float complex*)(s->k + h * head_size);
    for (int i = 0; i < head_size / 2; i++) {
        float complex f = freq_cis_real_row[i] + freq_cis_imag_row[i] * I;
        q_c[i] *= f;
        k_c[i] *= f;
    }
}
```

image

Loop check is:
```nasm
inc     rdi
mov     eax, [rsp+128h+head_size]
mov     ebp, eax
shr     ebp, 1Fh
add     ebp, eax
sar     ebp, 1
movsxd  rbp, ebp
cmp     rdi, rbp
```

Which for some reason still recalculates divison by 2, if you make it constant - code generation, once again, tries to utilise wider lanes if possible.

**Comment by mrsteyk** [comment]
I think most of it is just hints that we know that our sizes are divisible by a certain number.

**Comment by karpathy** [comment]
Hi all on this thread, thank you for this PR! I don't think that I like the use of complex.h:

- some platforms might not have complex.h
- it hides away lines of code into some library. i'm guessing a lot of people might not know what complex numbers are, how they work, and it makes it look scary, when nothing scary at all is happening in there.

I would accept a PR that makes RoPE more efficient, but sticking to a re-shuffled fully real-valued implementation. I am also likely to accept the same on the training side, where I think I will accept the PR that refactors the use of torch.complext64 in model.py, which as we saw leads to a ton of problems already, e.g. torch.compile being broken.

**Comment by mrsteyk** [comment]
Emits `idiv` for me.

**Comment by karpathy** [comment]
pushed the change here: 
https://github.com/karpathy/llama2.c/commit/0447b06e7c30a12ff37d4e34d700065405025439

will close this because there is no need to import complex.h, the complexity is not worth it imo.

**Pull request closed without merging**
