### PR TITLE
Added support for OpenBLAS

### PR DESCRIPTION
**Pull request by rdentato**
OpenBLAS performs slightly worse than openmp on my machine. 
Nevertheless is around a 5x improvement over the plain CPU run.

### CODE REVIEW

**Comment by karpathy** [comment]
If OpenBLAS is worse then why add it

**Comment by xefoci7612** [comment]
> OpenBLAS performs slightly worse than openmp on my machine. Nevertheless is around a 5x improvement over the plain CPU run.

@rdentato can you make it work in multi-thread? Does the cblas_sgemv() call start parallel threads to do the work? If not, I'm afraid it's a hard sell...

I don't know BLAS, so I can't help on this one.

**Comment by rdentato** [comment]
I think this is worthwile to investigate further if anyone confirms that there are cases where openmp is not available and openBLAS is. 
Otherwise, I would just rely on OpenMP and discard the PR.

**Comment by karpathy** [comment]
no gain no pain

**Pull request closed without merging**
