### PR TITLE
set n0 step count after building transformer

### PR DESCRIPTION
**Pull request by twobob**

### CODE REVIEW

**Comment by rdentato** [comment]
Why?

**Comment by twobob** [comment]
> Why?

because the code currently sets steps to 0 in the event of -n not being set  or <= 0 
and
    fprintf(stderr, "  -n <int>    number of steps to run for, default 256. 0 = max_seq_len\n");
says we should do otherwise.  which is more reasonable.

**Comment by twobob** [comment]
> I proposed the same in PR#327. @karpathy merged it but decided not to keep `-n 0` as a request to have the max seq length. (at the moment is my last message on the Discord channel) :)

okay. Then here is another simple chance for him to decide that which he would prefer. 
A reasonable person might expect to not have to know how many steps to allow. :)

**Comment by rdentato** [comment]
Yep, sorry I didn't read your first comment in full and did not get it .

If you have a look at my PR, I proposed these check to be closer to the loop that generates the text so to be ready for the "chat mode".  I guess will come to something similar in due time.

**Comment by karpathy** [comment]
pushed fix, closing.

**Pull request closed without merging**
