### PR TITLE
Slightly tighten init logic

### PR DESCRIPTION
**Pull request by ozabluda**
1. Reuse open file. This removes race condition between 2 open of the same file.
2. Remove unused variables.

### CODE REVIEW

**Comment by karpathy** [comment]
Sorry I'm not sure I understand the race condition or this fix.

**Comment by ozabluda** [comment]
`FILE *file = fopen(checkpoint, "rb");`

File "checkpoint.bin" is replaced any time between fopen() and open()

`fd = open(checkpoint, O_RDONLY); // open in read only mode`

`fd` now refers to the new (i.e. completely different) file.

**Comment by karpathy** [comment]
I think right now I clean up all the resources explicitly and don't leave anything "hanging", even if it's cleaned up by the OS. I'll try to maintain that for now.

**Comment by ozabluda** [comment]
You currently `exit()` from here without cleaning up `mmap()` or succesfull `calloc()`
https://github.com/karpathy/llama2.c/blob/d73b917d3ba7a1d933c65b1f33ecb58fd8d78a92/run.c#L97C9-L97C28

I can preserve `munmap()`, while removing the unnecessary `open()` with the race condition. Maybe it does serve some purpose, like helping with sanitizers, not sure.

**Pull request closed without merging**
