### PR TITLE
Speed up tinystories pretokenize command

### PR DESCRIPTION
**Pull request by mzcu**
Brings massive speedup on systems with larger number of cores - on my 5950X, run time is cut down from around 1 hour to 2 minutes

### CODE REVIEW

**Comment by richinseattle** [comment]
This is great, took my pretokenize time from an hour to 38sec.

**Comment by karpathy** [comment]
Is that juat because max_workers is hardwired to be 8 right now? Did you try removing that kwargs to get the system defaults, but still using threads?

**Comment by karpathy** [comment]
appreciated ty

**Comment by Majdoddin** [comment]
@karpathy 

> Is that juat because max_workers is hardwired to be 8 right now? Did you try removing that kwargs to get the system defaults, but still using threads?

No, @mzcu replaced ThreadPoolExecutor with ProcessPoolExecutor. Because of GIL, threading is mostly ineffective in python. 
Interestingly, they [decided](https://discuss.python.org/t/a-steering-council-notice-about-pep-703-making-the-global-interpreter-lock-optional-in-cpython/30474) for [nogil](https://github.com/colesbury/nogil) just a few days ago, but from python 3.13.

**Pull request merged**
