### PR TITLE
Proper cmd line argument parsing

### PR DESCRIPTION
**Pull request by tring27**
Not so poor anymore, adding some homegrown command line argument parsing to the c code.

### CODE REVIEW

**Comment by karpathy** [comment]
So actually I like something like this, but I want the checkoint to be required positional first arg. The rest of them to be optional kwargs

**Comment by tring27** [comment]
With this PR, checkpoint is a required arg, rest all are optional.
Its just that the position of any args are flexible. So as long as user provides a `-cp` the executable will run, otherwise it will print the usage menu.

**Comment by trholding** [comment]
Oops, I didn't see this one. 

Here is an alternate approach which I implemented in my fork.

https://github.com/karpathy/llama2.c/pull/222

**Comment by karpathy** [comment]
Closing this one but looking at #222

**Pull request closed without merging**
