### PR TITLE
Add build step for win64 msys2/mingw

### PR DESCRIPTION
**Pull request by tairov**
As it was suggested in the PR #149 I've implemented additional CI step for mingw (x86_64) compilation check.

### CODE REVIEW

**Comment by kroggen** [comment]
Thanks! The cool thing about CI is that we can see that it is working

**Comment by tairov** [comment]
@kroggen , exactly.. One additional step further we need in CI is a small test 😃 
In some cases I was experiencing binaries crashes, though compilation was successful. 

@karpathy do you have any idea how can we embed little test model into CI process to verify binaries?

**Comment by kroggen** [comment]
If using temperature `0` and a fixed prompt, then it must generate the same output deterministically

So it can work as a regression test

The small 15M model could be downloaded. I just don't know about GitHub Actions limits

**Comment by kroggen** [comment]
Maybe using the `cache` action to store the model?

https://github.com/actions/cache#example-cache-workflow

Then the jobs can check if the file is there on the sub-folder, and download it only if not

**Comment by karpathy** [comment]
One idea is to generate the weights with a known rng seed, and then sample in a known-good implementation, and then expect that sequence of tokens?

**Pull request merged**
